### ISSUE TITLE
feature request: karma config export

### ISSUE THREAD

**Issue by luqven** [xeroxinteractive/browserslist-tools#661]
## Description
Currently, the package defaults to `formatForSelenium`. There is no other configuration supported out of the box.

## Proposed solution
We could add a `formatForKarma` that modifies the returned object to match the karma config requirements in the config object.

Something along these lines:

``` js
import { BrowserFilter, OperatingSystemFilter }, getCapabilities from 'browserslist-browserstack';

const capabilities = await getCapabilities({
  username: 'browserstack-username',
  accessKey: 'browserstack-accesskey',
  browsers: {
    include: [
      BrowserFilter.CHROME
    ]
  },
  operatingSystems: {
    exclude: [
      OperatingSystemFilter.OSX
    ]
  },
  formatForKarma: true,
})

// returns
{
  base: "BrowserStack",
  browser: "chrome",
  browser_version: "90",
  os: "WINDOWS",
  os_version: "10"
}
```

## Considered alternatives

Instead, there could be a `plugins` framework where the returned object could go through a custom parser that reshapes it according to the `plugin`. This way, the package could support more testing frameworks without having to codify each one into the codebase.

Something along these lines:

``` js
import { BrowserFilter, OperatingSystemFilter }, getCapabilities from 'browserslist-browserstack';

const karma = (obj) => {
  // some formatting logic
}

const capabilities = await getCapabilities({
  username: 'browserstack-username',
  accessKey: 'browserstack-accesskey',
  browsers: {
    include: [
      BrowserFilter.CHROME
    ]
  },
  operatingSystems: {
    exclude: [
      OperatingSystemFilter.OSX
    ]
  },
  // for every plugin in the array, a key with a corresponding config object would be added to the return value
  plugins: [ karma ]
});

// returns -->

{
...
  karma: { 
    base: "BrowserStack",
    browser: "chrome",
    browser_version: "90",
    os: "OSX",
    os_version: "10"
  },
}
```

I'm happy to take on a PR for this if there's no objection to adding this feature 😀

**Comment by AndrewLeedham** [comment]
- `formatForKarma` seems strange alongside `formatForSelenium`.
- `plugins` seems excessive, since all it is doing is remapping an object.

## A few other alternatives.
- `format` which could accept `browserstack` | `selenium` | `karma`
- Remove the `formatForSelenium` option and expose a function to format the capabilities for selenium, making it more obvious how one might do the same themselves, without needing to extend the core API.

I think my preference would be `format`, given there aren't all that many formats out there I think keeping them in the project is fine, and they aren't much hassle to maintain. Also, if someone really wants to they can map any of the formats, to the format they desire.

**Comment by luqven** [comment]
@AndrewLeedham 

I decided to do a little bit of both in #662.

- kept the default behavior (format for selenium)
- created a `format` key that accepts a function or `false`
- exported two helpers, `formatForSelenium` and `formatForKarma` 

Let me know what you think 😄
